### ISSUE TITLE
When recovery is unfinished, Trezor still retains the new label

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-mcu#229] opened 2017-10-25 17:26 UTC
When user is doing recovery, and the recovery is unfinished (for example, wrong seed word written down), the uninitalized device still has the new label.

(Happens on 1.5.2, not sure about master)

**Comment by runn1ng** [comment] 2017-10-25 17:34
I have edited the original name, since reset behaviour is a little different and probably worse - see #230

**Comment by saleemrashid** [comment] 2017-10-26 13:57
I cannot reproduce this on `master` or 1.5.2. Could you be more specific?

**Comment by prusnak** [comment] 2017-11-14 13:07
Also cannot reproduce on `1.5.2` or `master` :-/

**Comment by prusnak** [comment] 2018-02-20 16:51
Closing. Please reopen if you can reproduce on master.

**Closed by prusnak** 2018-02-20 16:51 UTC
